-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 20:40:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema elearning_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elearning_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearning_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `elearning_app` ;

-- -----------------------------------------------------
-- Table `elearning_app`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cate_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `hour_count` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `last_update` VARCHAR(255) NULL DEFAULT NULL,
  `leture_count` INT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `promotion_price` DOUBLE NULL DEFAULT NULL,
  `view_count` INT NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `position` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlu4ce0f8di1r2c4txhlav2v27` (`cate_id` ASC) VISIBLE,
  CONSTRAINT `FKlu4ce0f8di1r2c4txhlav2v27`
    FOREIGN KEY (`cate_id`)
    REFERENCES `elearning_app`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`targets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`targets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKoyy2lgy3w04ylavtb7paw1v1d` (`course_id` ASC) VISIBLE,
  CONSTRAINT `FKoyy2lgy3w04ylavtb7paw1v1d`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `elearning_app`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`user_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`user_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL DEFAULT NULL,
  `course_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKb84hga2qpwc4vv44lmyb8mwux` (`course_id` ASC) VISIBLE,
  INDEX `FK5i2mwg17kvpk92fy6cdii93da` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK5i2mwg17kvpk92fy6cdii93da`
    FOREIGN KEY (`user_id`)
    REFERENCES `elearning_app`.`users` (`id`),
  CONSTRAINT `FKb84hga2qpwc4vv44lmyb8mwux`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `elearning_app`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning_app`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL DEFAULT NULL,
  `time_count` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrccvc1a5qx2dqsyienwhuk66j` (`course_id` ASC) VISIBLE,
  CONSTRAINT `FKrccvc1a5qx2dqsyienwhuk66j`
    FOREIGN KEY (`course_id`)
    REFERENCES `elearning_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
